version: "3.9"

services:
  db:
    image: postgres:16
    container_name: greco_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: greco
      POSTGRES_PASSWORD: greco_pass
      POSTGRES_DB: greco_shop
    ports:
      # Endre ekstern port til 5433 for å unngå konflikt hvis noe annet bruker 5432
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  db_data:


